### ISSUE TITLE
Lollipop date is not change in "time" mode 

### ISSUE THREAD

**Issue by aramgev** [VitaliiBlagodir/cordova-plugin-datepicker#101]
var options = {                
        date: myDate,
        mode: 'time'
}; 
window.plugins.datePicker.show( options, function(date) {
        alert(date);
});

Value of date is equal of myDate, no matter what I choose.

**Comment by roberthovhannisyan** [comment]
+1
This issue appears on Lollipop when androidTheme is set to particularly THEME_DEVICE_DEFAULT_DARK

**Comment by roberthovhannisyan** [comment]
It seems that the bug is observed only on Android 5.0 and was fixed in 5.1
See https://code.google.com/p/android/issues/detail?id=78861
However threre are a lot of Android devices which didn't get the 5.1 and we have to find some workaround to make the plugin work on 5.0.
As I understand it can be fixed by modifying the following line 
https://github.com/VitaliiBlagodir/cordova-plugin-datepicker/blob/master/src/android/DatePickerPlugin.java#L127
by this
```
timeDialog.setButton(DialogInterface.BUTTON_POSITIVE, labelOk, timeDialog);
```
The reason why mentioned coded is supposed to resolve the issue is that the code from the following plugin https://github.com/okaybmd/cordova-plugin-datepicker/blob/master/src/android/DatePickerPlugin.java works correctly on 5.0

Hope it will help to resolve the issue

**Comment by jgillard** [comment]
This worked for me, thank you so much!

**Comment by jheander** [comment]
I get the same issue even when theme is set to THEME_DEVICE_DEFAULT_LIGHT.

**Comment by jheander** [comment]
@roberthovhannisyan Your fix solves the problem for me too. Could you send a pull request to this project so we could get a new npm release that is working for Lollipop?

**Comment by VitaliiBlagodir** [comment]
@jheander, good job! Thanks!
